UPDATE public.parametro SET valor = '1.4.0' WHERE codigo = 'versao_database';

ALTER TABLE DIREITO DROP CONSTRAINT PK_DIREITO;

ALTER TABLE DIREITO ADD ID_DIREITO SERIAL NOT NULL;

ALTER TABLE DIREITO ADD CONSTRAINT PK_DIREITO PRIMARY KEY( ID_DIREITO );

